- name: Apply basic configuration for connect node
  hosts: connect
  gather_facts: false
  roles:
    - ssh
    - k8s_install
  tasks:
    - ansible.builtin.include: roles/connect/tasks/setup_certificate.yaml


- name: Apply configuration for masters
  hosts: masters
  gather_facts: true
  roles:
    - ssh
    - common
    - master

- name: Apply configuration for workers
  hosts: workers
  gather_facts: false
  roles:
    - ssh
    - common
    - worker

- name: Apply configuration for connect kubeconfig
  hosts: connect
  gather_facts: true
  tasks:
    - ansible.builtin.include: roles/connect/tasks/kubeconfig.yaml


