
- name: Registry setup
  tags: reg
  hosts: ['registry', 'connect'] # wywalic connect stad
  gather_facts: true
  roles:
    - ssh
    - registry


- name: Apply basic configuration for connect node
  hosts: connect
  gather_facts: false
  roles:
    - ssh
    - k8s_install
  tasks:
    - name: Setup certificate for connect
      ansible.builtin.include_tasks:
        file: roles/connect/tasks/setup_certificate.yaml

- name: Ssh and common
  hosts: ['masters', 'workers']
  gather_facts: true
  roles:
    - ssh
    - common

- name: Apply configuration for masters
  hosts: masters
  gather_facts: true
  roles:
    - master
  tasks:
    - name: Setup certificate for connect
      ansible.builtin.include_tasks:
        file: roles/master/tasks/certificate.yaml
      when: not hostvars[groups['connect'][0]].csr.stat.exists

- name: Apply configuration for workers
  hosts: workers
  gather_facts: false
  roles:
    - worker

- name: Apply configuration for connect kubeconfig
  hosts: connect
  gather_facts: true
  tasks:
    - name: Kubeconfig
      ansible.builtin.include_tasks:
        file: roles/connect/tasks/kubeconfig.yaml
      when: not csr.stat.exists

