- name: Apply configuration for connect
  hosts: connect
  gather_facts: false
  roles:
    - ssh
    - k8s_install
    - connect


- name: Apply configuration for masters
  hosts: masters
  gather_facts: true
  roles:
    - ssh
    - common
    - master

- name: Apply configuration for workers
  hosts: workers
  gather_facts: false
  roles:
    - ssh
    - common
    - worker

