- name: Install python3-pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Install requirements for k8s installation
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Add Kubernetes official GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://dl.k8s.io/apt/doc/apt-key.gpg
    state: present


- name: Add Kubernetes Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install k8s packages
  vars:
    pkgs: 
      - kubectl
      - "{{ 'kubelet' if 'connect' not in group_names  }}"
      - "{{ 'kubeadm' if 'connect' not in group_names }}"
  become: true
  ansible.builtin.apt:
    pkg:
      - "{{ item }}"
    state: present
  loop: "{{ pkgs |select()}}"

    
- name: Add kubectl alias
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: alias 'k'='kubectl'
    mode: '0644'
    create: true

- name: Create a $HOME/.kube if it does not exist
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'

- name: Install kubernetes python package
  become: true
  ansible.builtin.pip:
    name: kubernetes
