- name: Reboot machine
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: Restart containerd
  become: true
  ansible.builtin.service:
    name: containerd
    state: restarted
