- name: Install requirements for containerd installation
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install requirements for containerd installation
  ansible.builtin.apt:
    name: containerd.io
    state: present

- name: Create continerd.conf
  copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

- name: Create config for containerd (SystemdCgroup true)
  ansible.builtin.copy: 
    src: files/containerd.config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart containerd

- name: Flush handlers
  meta: flush_handlers

- name: Start and enable containerd
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true
