- name: Install requirements for containerd installation
  become: true
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Create /etc/apt/keyrings directory
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Setup Docker
  become: true
  vars:
    os: "{{ 'raspbian' if rpi else 'ubuntu' }}"
    arch: "{{ 'armhf' if rpi else 'amd64' }}"
    os_type: "{{ 'bullseye' if rpi else 'jammy' }}"
  block:
    - name: Add signing key for Docker
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ os }}/gpg" 
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
    - name: Add Docker Repository
      ansible.builtin.apt_repository: #
        repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ os }} {{ os_type }} stable"
        state: present
        update_cache: true


- name: Install containerd
  become: true
  ansible.builtin.apt:
    name: containerd.io
    state: present

#- meta: end_play

- name: Create continerd.conf
  become: true
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'


- name: Start and enable containerd
  become: true
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true

- name: Create config for containerd (SystemdCgroup true)
  become: true
  ansible.builtin.copy:
    src: files/containerd.config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart containerd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
