- name: Check if temporary swap is disabled
  register: total_swap
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      cat /proc/meminfo | grep SwapTotal: | awk '{ print $2 }'
  args:
    executable: /bin/bash
  changed_when: false

- name: Disable swap temporary
  become: true
  ansible.builtin.command: swapoff -a
  when: total_swap.stdout | int != 0

######## to be fixed risky shell pipe

- name: Check if permanent swap is disabled
  register: swap_fstab
  ansible.builtin.shell: cat /etc/fstab | grep swap | head -c 1
  args:
    executable: /bin/bash
  changed_when: false

##########

- name: Create k8s modules config
  become: true
  vars:
    text: |
      overlay
      br_netfilter
  ansible.builtin.copy:
    content: "{{ text }}"
    dest: /etc/modules-load.d/k8s.conf
    mode: '0644'
  register: k8s_kernel_modules


- name: Add kernel modules
  become: true
  ansible.builtin.command: "modprobe {{ item }}"
  when: k8s_kernel_modules.changed
  loop:
    - overlay
    - br_netfilter

- name: Create bridged traffic config
  become: true
  ansible.builtin.copy:
    src: files/bridged.traffic.conf
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
  register: sysctl_k8s

- name: Load kernel settings
  become: true
  ansible.builtin.command: sysctl -p --system
  when: sysctl_k8s.changed
