# one master only for now
# do not do this every time, check /etc/kubernetes/pki directory
# sudo kubeadm reset -f
- name: Initialize k8s cluster
  vars:
    do_init: true
  ansible.builtin.shell: kubeadm init --upload-certs --token {{ token }} --kubernetes-version latest --apiserver-advertise-address {{ hostvars[groups['masters'][0]].private_ip  }} --skip-certificate-key-print --skip-token-print
  #ignore_errors: true
  failed_when: init_output.rc != 0
  register: init_output


# call this on master node !
- name: Get join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  failed_when: join_command.rc != 0
  register: join_command
  when: inventory_hostname i== groups['masters'][0]
