- name: Check if /etc/kubernetes/pki is empty before init
  ansible.builtin.find:
    paths: /etc/kubernetes/pki
  register: files_found

- name: Initialize k8s cluster
  become: true
  ansible.builtin.command:
    cmd: >
      kubeadm init --upload-certs --token
      {{ token }} --kubernetes-version latest
      --apiserver-advertise-address {{ hostvars[groups['masters'][0]].private_ip }}
      --skip-certificate-key-print --skip-token-print
  failed_when: init_output.rc != 0
  register: init_output
  when: files_found.matched == 0 and inventory_hostname == groups['masters'][0]
  notify:
    - Create a $HOME/.kube if it does not exist
    - Copy admin.conf for kubectl
    - Apply calico manifest
    - Set env for Calico


- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Get join command
  become: true
  ansible.builtin.command: kubeadm token create --print-join-command
  failed_when: join_command.rc != 0
  register: join_command
  when: inventory_hostname == groups['masters'][0]


- name: Read admin.conf on first master node for copying to worker nodes
  become: true
  ansible.builtin.command: cat /etc/kubernetes/admin.conf
  changed_when: false
  register: admin_conf
  when: inventory_hostname == groups['masters'][0]
