# - name: Create kubeconfig
#   ansible.builtin.template:
#     src: roles/connect/templates/kubeconfig.j2
#     dest: "/home/{{ ansible_user }}/.kube/config"
#   when: hostvars[groups['masters'][0]].crt_result and not stat_result.stat.exists
