- name: Store client certificate
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.kube/client.crt"
    content: "{{ hostvars[groups['masters'][0]].client_certificate.stdout | b64decode }}"
    mode: '0600'
  # when: not stat_result.stat.exists # ??? if config exists ???

- name: Store client certificate
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.kube/ca.crt"
    content: "{{ hostvars[groups['masters'][0]].ca_file.stdout }}"
  #when: not stat_result.stat.exists # ???


- name: Create kubeconfig
  ansible.builtin.template:
    src: roles/connect/templates/kubeconfig.j2
    dest: "/home/{{ ansible_user }}/.kube/config"
  when: hostvars[groups['masters'][0]].client_certificate is defined



# - name: test
#   tags: t1
#   debug:
#     msg: "{{ .stdout}}"
# 
