- name: TEST
  ansible.builtin.debug:
    msg:  "{{ private_key.privatekey | b64encode }}"

- name: TEST
  ansible.builtin.debug:
    msg:  "{{  hostvars[groups['masters'][0]].ca_file.stdout | b64encode}}"

- name: TEST
  ansible.builtin.debug:
    msg:  "{{ hostvars[groups['masters'][0]].crt_result.certificate | b64encode }}"

- name: Create kubeconfig
  ansible.builtin.template:
    src: roles/connect/templates/kubeconfig.j2
    dest: "/home/{{ ansible_user }}/.kube/config"
  when: hostvars[groups['masters'][0]].crt_result and not stat_result.stat.exists
