- name: Check that the kube config exists
  stat:
    path: "/home/{{ ansible_user }}/.kube/config"
  register: stat_result


- name: Generate an OpenSSL private key
  community.crypto.openssl_privatekey_pipe:
      size: 2048
  register: private_key
  no_log: true
  when: not stat_result.stat.exists

- name: Store private_key
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.kube/{{ ansible_user }}-k8s.key"
    content: "{{ private_key.privatekey }}"
  when: not stat_result.stat.exists

- name: Generate an OpenSSL Certificate Signing Request with an inline CSR
  community.crypto.openssl_csr_pipe:
    privatekey_content: "{{ private_key.privatekey }}"
    common_name: "{{ common_name }}"
    organization_name: "{{ org_name }}"
  register: csr_result
  when: not stat_result.stat.exists
