- name: Check is csr file exists
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/.kube/client.csr"
  register: csr

- name: Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "/home/{{ ansible_user }}/.kube/client.key"


- name: Generate csr
  when: not csr.stat.exists
  block:
  - name: Generate an OpenSSL Certificate Signing Request
    community.crypto.openssl_csr:
      path: "/home/{{ ansible_user }}/.kube/client.csr"
      privatekey_path: "/home/{{ ansible_user }}/.kube/client.key"
      common_name: "{{ common_name }}"
      organization_name: "{{ org_name }}"
  - name: Read csr file into memory
    become: true
    ansible.builtin.command: cat "/home/{{ ansible_user }}/.kube/client.csr"
    changed_when: false
    register: client_csr
